### ISSUE TITLE
doesn't work if panels are used

### ISSUE THREAD

**Issue by Lehnerr** [bickart/SugarCRM-Banded-Record-View#1]
Hi Jeff.

I've tested and it works fine, if the record has only one panel. If there are more panels, all even panels are filled with the background color.
Any idea how to solve this?

kindest regards Robert

**Comment by bickart** [comment]
Can you indicate which version of Sugar you are using and include an image? I'm not following your description

**Comment by Lehnerr** [comment]
Hi.

Im using Sugarcrm Pro 7.6.1 .

Attached you can see the sceenshot. The second panel is grey.

kindest regrads robert

**Comment by bickart** [comment]
The image didn't come through.. can you link to it?

**Comment by Lehnerr** [comment]
Here it is
![29-02-_2016_19-23-02](https://cloud.githubusercontent.com/assets/16813374/13404862/16299a34-df1c-11e5-9e87-a62ad2a8f2e6.png)

**Comment by bickart** [comment]
You closed the issue. Anyway... it looks like it is a CSS issue. If you look at the custom.less you'll see we are using some "magic" to determine which rows should get background color. I'd have to review the CSS that sugar is generating for the 2nd panel and see what the styles are.

**Comment by Lehnerr** [comment]
Hi.

I've added the even css too and now it works:

.row-fluid:nth-of-type(even) {
  background-color: #fff;
  border-color: #ccc;
  color: #888;
}

.row-fluid:nth-of-type(odd) {
  background-color: #eee;
  border-color: #ccc;
  color: #888;
}

.record-label {
  font-weight: bold !important;
}

**Comment by bickart** [comment]
I added the new (even) code into the branch based upon your feedback. Thanks for solving the issue. You could have submitted a pull request to get it integrated.
